# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This file creates the ingress rules for OAM
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oamadmin-ingress
  namespace: <OAMNS>
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "2000k"
    nginx.ingress.kubernetes.io/enable-access-log: "false"
    nginx.ingress.kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: <OAM_ADMIN_LBR_HOST>
    http:
      paths:
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /console
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /consolehelp
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /rreg/rreg
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /em
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /oamconsole
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /dms
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /oam/services/rest
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /iam/admin/config
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /oam/admin/api
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /iam/admin/diag
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /oam/serices
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /iam/admin
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /oam/services/rest/11.1.2.0.0
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-adminserver
            port:
              number: <OAM_ADMIN_PORT>
        path: /em
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /oam/services/rest/ssa
        pathType: Prefix
      - backend:
          service:
            name: <OAM_DOMAIN_NAME>-cluster-policy-cluster
            port:
              number: 15100
        path: /access
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oamruntime-ingress
  namespace: <OAMNS>
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "2000k"
    #nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: <OAM_LOGIN_LBR_HOST>
    http:
      paths:
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /ms_oauth
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /oam/services/rest/auth
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /oam/services/rest/access
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /oamfed
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /otpfp/
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /oauth2
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /oam
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /.well-known/openid-configuration
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /.well-known/oidc-configuration
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /CustomConsent
        pathType: Prefix
      - backend:
          service:
            name:  <OAM_DOMAIN_NAME>-cluster-oam-cluster
            port:
              number: 14100
        path: /iam/access
        pathType: Prefix
---
