#
# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
oudConfig:
  rootUserPassword: %ROOT_USER_PASSWORD%
  sampleData: 10
  cleanupbeforeStart: true 

image:
  repository: %IMAGE_REPO%
  tag: %IMAGE_TAG%

busybox:
  image: %BUSYBOX_IMAGE% 

persistence:
  enabled: true
  storageClass: manual
  type: filesystem
  filesystem:
    hostPath:
      path: %USER_PROJECTS_PATH%
  size: 30Gi

configVolume:
  enabled: false
  storageClass: manual
  type: filesystem
  filesystem:
    hostPath:
      path: %USER_PROJECTS_PATH%
  size: 10Gi

replicaCount: 3

ingress:
  enabled: true
  type: nginx
  tlsEnabled: true

service:
  allSvcEnabled: true
  allSvcType: ClusterIP
