#
# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- if and .Values.persistence.enabled (not .Values.persistence.pvcname) }}
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "oud-ds-rs.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "oud-ds-rs-pv.labels" . | nindent 4 }}
    type: {{ template "oud-ds-rs.fullname" . }}-pvc
spec:
{{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
  selector:
    matchLabels:
      {{- include "oud-ds-rs-pv.labels" . | nindent 6 }}
      type: {{ template "oud-ds-rs.fullname" . }}-pv
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
