#
# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oud-ds-rs.fullname" . }}-0
  labels:
    {{- include "oud-ds-rs.labels" . | nindent 4 }}
    oud/instance: {{ include "oud-ds-rs.fullname" . }}-0
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.oudPorts.adminldaps }}
      name: adminldaps
      targetPort: adminldaps
      protocol: TCP
    - port: {{ .Values.oudPorts.adminhttps }}
      name: adminhttps
      targetPort: adminhttps
      protocol: TCP
    - port: {{ .Values.oudPorts.replication }}
      name: replication
      targetPort: replication
      protocol: TCP
  selector:
    {{- include "oud-ds-rs.selectorLabels" . | nindent 4 }}
    oud/instance: {{ include "oud-ds-rs.fullname" . }}-0
