baseURL = "/fmw-kubernetes/20.3.3/"
languageCode = "en-us"
title = "Oracle Fusion Middleware on Kubernetes"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# disable the copy to clipboard links
disableInlineCopyToClipBoard = true

publishDir = "docs"

# analytics
googleAnalytics = "UA-129126578-2"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
