# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion -}}
{{- if eq .Values.type "NGINX" }}
{{- if or (eq .Values.sslType "NONSSL") (eq .Values.sslType "SSL") }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-nginx
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: 'cookie'
    nginx.ingress.kubernetes.io/session-cookie-name: 'sticky'
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/enable-access-log: 'false'
    kubernetes.io/ingress.class: 'nginx'
{{- if (.Values.nginxTimeOut) }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: '{{ .Values.nginxTimeOut }}' 
    nginx.ingress.kubernetes.io/proxy-send-timeout: '{{ .Values.nginxTimeOut }}'
{{- end }}
{{- if eq .Values.sslType "SSL" }}  
    nginx.ingress.kubernetes.io/proxy-buffer-size: '2000k'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Forwarded-Proto: https";
      more_set_input_headers "WL-Proxy-SSL: true";
    nginx.ingress.kubernetes.io/ingress.allow-http: 'false'
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /console
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /em
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /soa
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.soaClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.soaManagedServerPort }}
      - path: /integration
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.soaClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.soaManagedServerPort }}
      - path: /soa-infra
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.soaClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.soaManagedServerPort }}
      - path: /identity
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /admin
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /oim
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /sysadmin
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /workflowservice
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /xlWebApp
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /Nexaweb
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /callbackResponseService
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /spml-xsd
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /HTTPClnt
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /reqsvc
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /iam
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /provisioning-callback
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /CertificationCallbackService
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /ucs
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /FacadeWebApp
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /OIGUI
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /weblogic
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oimManagedServerPort }}
         
{{- end }}
{{- end }}
{{- end }}

